---
# Create the namespace
apiVersion: v1
kind: Namespace
metadata:
  name: ns-srv-inem
  labels:
    purpose: production
    app: app-inem
    owner: ti-sercom
---
# Enforce limit resources within the namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-srv-inem
  namespace: ns-srv-inem
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 500Mi
    limits.cpu: "8"
    limits.memory: 3Gi
---
# Deploy the web application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-app-inem
  namespace: ns-srv-inem
  labels:
    deploy: dp-app-inem
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dp-app-inem
  template:
    metadata:
      labels:
        app: dp-app-inem
    spec:
      containers:
      - name: ctd-app-inem
        image: capso/capsoweb:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 600Mi
            cpu: 1
          requests:
            memory: 300Mi
            cpu: 500m
