apiVersion: apps/v1
kind: Deployment
metadata:
  name: prodpod1-deployment
  namespace: production
  labels:
    deploy: prodapp1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prodapp1
  template:
    metadata:
      labels:
        app: prodapp1
    spec:
      containers:
      - name: prodctd1
        image: capso/capsonet:latest
        imagePullPolicy: Always