apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: development-deny-ingress
  namespace: development
spec:
  podSelector:
    matchLabels:
      app: devapp1
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:  
          purpose: development